=head1 NAME

XML::LibXML::DocumentFragment - DOM L2 Implementation of a Document Fragment

=head1 DESCRIPTION




This class is a helper class as described in the DOM
Level 2 Specification. It is implamented as a node
without name. All adding, inserting or replacing
functions are aware about document fragments now.





As well B<all> unbound nodes (all nodes that
does not belong to any document subtree) are implicit
member of document fragments.




=head1 AUTHOR

Matt Sergeant, Christian Glahn

=head1 SEE ALSO

XML::LibXML, XML::LibXML::Node, XML::LibXML::Element, XML::LibXML::Document, XML::LibXML::Text, XML::LibXML::Comment, XML::LibXML::CDATASection

=head1 VERSION

1.53

