# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-Simple
version:      2.11
version_from: lib/XML/Simple.pm
installdirs:  site
requires:
    Test::Simple:                  0.41
    XML::NamespaceSupport:         1.04
    XML::SAX:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.20
